apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app-container
        image: veerrkrk/libraryproject:latest
        ports:
          - containerPort: 3006
        env:
         - name: MONGODB_URI
           value: "mongodb://nodejsproject:27017/library_management"
      - name: nodejsproject
        image: mongo:latest
        ports:
           - containerPort: 27017